server:
  port: 8080

spring:
  application:
    name: data-query-platform

  # 数据源配置 (主数据库 - PostgreSQL)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/data_query_platform
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/**/*.xml

# JWT配置
jwt:
  secret: DataQueryPlatformSecretKey2025ForJWTTokenGeneration
  expiration: 86400000  # 24小时

# 日志配置
logging:
  level:
    com.example.dataquery: debug
    org.springframework.web: info
    org.quartz: info
